name: AppSec LLM + Semgrep Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Semgrep and dependencies
        run: |
          curl -sL https://github.com/returntocorp/semgrep/releases/latest/download/semgrep-linux-amd64 -o semgrep
          chmod +x semgrep
          sudo mv semgrep /usr/local/bin/
          pip install openai requests python-dotenv jinja2

      - name: Run AppSec Scanner
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python cli.py --repo . --scan all

      - name: Comment findings on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: pr-findings.txt
